<?php

/**
 * Implements hook_menu().
 */
function term_delete_replace_menu() {
  $items['term_delete_replace/autocomplete/%/%'] = array(
    'title' => 'Autocomplete taxonomy replace',
    'page callback' => 'term_delete_replace_term_autocomplete',
    'access arguments' => array('access content'),
    'page arguments' => array(2, 3),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function term_delete_replace_form_taxonomy_form_term_alter(&$form, &$form_state, $form_id) {
  // Only modify the form if it is in the "Confirm Delete" mode.
  if (isset($form_state['confirm_delete']) && $form_state['confirm_delete'] === TRUE) {

    $form['description']['#markup'] = $form['description']['#markup'] . '<br /><br />' . t('You can replace any occurrences of the deleted term with another term by specifying the replacement term below. This is useful when correcting typos, or to consolidate multiple synonymous terms.');

    $form['replacement_term'] = array(
      '#type' => 'textfield',
      '#title' => t('Replacement term'),
      '#autocomplete_path' => 'term_delete_replace/autocomplete/' . $form['#vocabulary']->vid . '/' . $form['#term']->name,
    );

    array_unshift($form['#submit'], 'term_delete_replace_form_taxonomy_form_term_submit');
  }
}

/**
 * Adds the chosen term to all nodes that were using the deleted term.
 * If the chosen term doesn't exist, add it to the vocabulary first.
 */
function term_delete_replace_form_taxonomy_form_term_submit($form, &$form_state) {
  if (drupal_strlen($form_state['values']['replacement_term']) > 0) {

    $replacement_term_name = check_plain($form_state['values']['replacement_term']);

    $term = NULL;
    $existing_term = taxonomy_get_term_by_name($replacement_term_name);
    // Find out if the replacement term already exists.
    foreach ($existing_term as $potential) {
      if ($potential->vocabulary_machine_name == $form['#vocabulary']->machine_name &&
        $potential->name == $replacement_term_name) {
        $term = $potential;
      }
    }

    // Check if the replacement term is the same as the deleted term. In that case, tell that to the user and return.
    if ($term && $term->tid == $form['#term']->tid) {
      drupal_set_message(t('Please select another replacement term, cannot replace the a deleted term with itself.'), 'error');
      $form_state['values']['delete'] = FALSE;
      return;
    }

    // Create and save the replacement term if it doesn't exist.
    if (!$term) {
      $term = new stdClass();
      $term->name = $form_state['values']['replacement_term'];
      $term->description = NULL;
      $term->format = filter_fallback_format();
      $term->weight = -10;
      $term->vid = $form['#vocabulary']->vid;
      $term->vocabulary_machine_name = $form['#vocabulary']->machine_name;

      $status = taxonomy_term_save($term);

      drupal_set_message(t('Created term @termname.', array('@termname' => $term->name)));
    }

    // Get all nodes containing fields referencing to the deleted term.
    $related_nodes_data = db_select('taxonomy_index', 'ti')
    ->fields('ti', array('nid', 'created', 'sticky'))
    ->condition('tid', $form['#term']->tid)
    ->execute();

    // If there are any nodes with fields containing references to the deleted term, add the replacement term to them.
    if (!empty($related_nodes_data)) {
      foreach ($related_nodes_data as $node_data) {
        $node = node_load($node_data->nid, NULL, TRUE);

        // Find the "vocabulary fields" containing the deleted term tid.
        $vocabulary_fields = _term_delete_replace_get_vocabulary_fields($node, $form['#term']->tid);

        if (!empty($vocabulary_fields)) {
          // Add the replacement term to the fields containining the deleted one.
          foreach ($vocabulary_fields as $fieldname) {
            // ToDo: Why do I have to use array_unshift? On push, the field api will remove the data for the wrong field in the field's table...
            // ToDo: Is the language of the term always the same as the language of the node?
            array_unshift($node->{$fieldname}[$node->language], array('tid' => $term->tid));
          }
        }
        else { // This shouldn't happen. But if it does, don't delete the term, just rebuild the form.
          drupal_set_message(t('Could\'nt find any field containing the deleted term tid, term references was not replaced.'), 'error');
          $form_state['values']['delete'] = FALSE;
          return;
        }

        // Save the node with the replacement term added.
        node_save((object) $node);
      }
    }

    // Tell user that replacement went successful.
    drupal_set_message(
      t(
        'Added term reference "@replace_name" to all nodes referencing to the deleted term.',
        array(
          '@replace_name' => $form_state['values']['replacement_term'],
        )
      )
    );
  }
}

/**
 * Autocomplete function for the replacement term textfield.
 */
function term_delete_replace_term_autocomplete($vid, $deleted_term_name, $typed) {
  $tree = taxonomy_get_tree($vid);
  $output = array();


  foreach ($tree as $i => $term) {
    $term_name = $term->name;

    /*
     * Check if the current term contains the characters it should.
     * Also check to see that the current term isn't the same as the deleted one, we dont't want that one.
     */
    if (strpos(drupal_strtolower($term_name), drupal_strtolower($typed)) !== FALSE && $term_name != $deleted_term_name) {
      // Term names containing commas or quotes must be wrapped in quotes.
      if (strpos($term_name, ',') !== FALSE || strpos($term_name, '"') !== FALSE) {
        $term_name = '"' . str_replace('"', '""', $term_name) . '"';
      }
      $output[$term_name] = $term_name;
    }
  }

  drupal_json_output($output);
}

/**
 * Helper function getting the vocabulary fields containing the term with specified tid.
 */
function _term_delete_replace_get_vocabulary_fields($node, $tid) {
  $fields = array();
  foreach ($node as $key => $item) {
    if (is_array($item) && isset($item[$node->language])) {
      foreach ($item[$node->language] as $fieldValue) {
        if (isset($fieldValue['tid']) && $fieldValue['tid'] == $tid) {
          $fields[] = $key;
        }
      }
    }
  }
  return $fields;
}

