<?php
// $Id$

/**
 * @file
 * TODO: Create a simple contact form block.
 */
 
/**
 * Implements hook_menu().
 */
function term_replace_menu() {
  $items['taxonomyreplace/autocomplete/%'] = array(
    'title' => 'Autocomplete taxonomy replace',
    'page callback' => 'term_replace_term_autocomplete',
    'access arguments' => array('access content'),
    'page arguments' => array(2),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

/**
*	Implements hook_form_alter().
*/
function term_replace_form_taxonomy_form_term_alter(&$form, &$form_state, $form_id) {
	if (isset($form['delete'])) {
		
		array_unshift($form['#submit'], 'term_replace_form_taxonomy_form_term_submit');
		
		$form['description']['#markup'] = t($form['description']['#markup'] . ' If you\'d like, you can replace the deleted term wherever it\'s used by entering a replacement term in the textfield below.'); 
		
		$form['replacement_term'] = array(
			'#type' => 'textfield',
			'#title' => t('Replacement term'),
			'#autocomplete_path' => 'taxonomyreplace/autocomplete/' . $form['#vocabulary']->vid,
		);
	}
}

/**
*	Adds te chosen term to all nodes that was using the deleted term.
* If the chosen term doesn't exist, add it to the vocabulary first.
*/
function term_replace_form_taxonomy_form_term_submit($form, &$form_state) {
	if (strlen($form_state['values']['replacement_term']) > 0) {
		$term = null;
		
		$existing_term = taxonomy_get_term_by_name($form_state['values']['replacement_term']);
		foreach ($existing_term as $potential) {
			if ($potential->vocabulary_machine_name == $form['#vocabulary']->machine_name && 
				$potential->name == $form_state['values']['replacement_term']) {
					$term = $potential;
			}
		}
		
		dsm($form);
		dsm($form_state);
		if ($term && $term->tid == $form['#term']->tid) {
			//drupal_set_message(t('Cannot replace a term with itself.'), 'error');
			form_set_error('replacement_term', t('Cannot replace a term with itself.'));
			$form_state['values']['delete'] = FALSE;
			return;			
		} else {
			$form_state['values']['delete'] = TRUE;
			//$form_state['rebuild'] = FALSE;
			//$form_state['confirm_delete'] = TRUE;
		}
		dsm($form_state);
		/*
			$form_state['rebuild'] = TRUE;
    $form_state['confirm_delete'] = TRUE;

		*/
		
		// Create the term if it does'nt exist.
		if (!$term) {
			$term = new stdClass();
			$term->name = $form_state['values']['replacement_term'];
			$term->description = NULL;
			$term->format = filter_fallback_format();
			$term->weight = -10;
			$term->vid = $form['#vocabulary']->vid;
			$term->vocabulary_machine_name = $form['#vocabulary']->machine_name;
			
	    $status = taxonomy_term_save($term);
	    
	    drupal_set_message(t('Created term %termname.', array	('%termname' => $term->name)));
		}
		
		$select_result = db_select('taxonomy_index', 'ti')
			->fields('ti', array('nid', 'created', 'sticky'))
			->condition('tid', $form['#term']->tid)
	  	->execute();
	  
	  // If there are any nodes containing the deleted term, add the replacement term to them.
	  if (!empty($select_result)) {
			$insert_query = db_insert('taxonomy_index')->fields(array('nid', 'tid', 'sticky', 'created', ));
	    foreach ($select_result as $item) {
	    	$node = node_load($item->nid, null, true);
	    		    	
	    	// Find the field containing the deleted term tid.
	    	// ToDo: Is the language of the term always the same as yhe language of the node?
	    	$term_field = null;
	    	foreach ($node as &$item) {
	    		if (is_array($item) && isset($item[$node->language])) {
	    			foreach ($item[$node->language] as $fieldValue) {
	    				if (isset($fieldValue['tid']) && $fieldValue['tid'] == $form['#term']->tid) {
	    					$term_field = &$item[$node->language];
	    					break;
	    				}
	    			}
	    			if ($term_field) break;
	    		}
	    	}
	    	
	    	if ($term_field) {
	    		// Add the replacement term to the field array.
	    		// ToDo: There may be more fields containing a reference to a term.
	    		// ToDo: Why do I have to use array_unshift?.
	    		array_unshift($term_field, array('tid' => $term->tid));
	    	} else {
	    		drupal_set_message(t('Could\'nt find the field containing the deleted term id.'), 'error');
	    	}
	    	
	    	// Save the node with the new replacement term added.
				node_save((object) $node);
	    }
		}
		
		drupal_set_message(
			t(
				'Added term "@replace_name" to all nodes containing the deleted term "@name".',
				array(
					'@replace_name' => $form_state['values']['replacement_term'],
					'@name' => $term->name
				)
			)
		);
  }
}

/**
*	Autocomplete helper function for the term replacement textfield.
*/
function term_replace_term_autocomplete($vid, $typed = '') {

	$tree = taxonomy_get_tree($vid);	
	$output = array();
	foreach ($tree as $i => $term) {
		$tn = $term->name;
		if (strpos(strtolower($tn), strtolower($typed)) !== FALSE) {
			// Term names containing commas or quotes must be wrapped in quotes.
			if (strpos($tn, ',') !== FALSE || strpos($tn, '"') !== FALSE) {
        $tn = '"' . str_replace('"', '""', $tn) . '"';
      }
			$output[$tn] = $tn;
		}
	}

	drupal_json_output($output);
}