<?php

/**
 *  Implementation of hook_permission():
 */
function term_merge_permission() {
  return array(
    'merge terms' => array(
      'title' => t('Merge terms'),
      'description' => t('Gives the user the ability to merge terms.'),
    )
  );
}

/**
 *  Implements hook_menu():
 */
function term_merge_menu() {
  $items = array(
    'admin/structure/taxonomy/merge/%' => array(
      'title' => 'Term merge',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('term_merge_term_merge_form', 4),
      'access arguments' => array('term merge'),
      'type' => MENU_CALLBACK,
    )
  );

  return $items;
}

/**
 *  Implements hook_form_FORM_ID_alter().
 *
 *  Inserts the Merge button into the actions area of the form.
 */
function term_merge_form_taxonomy_overview_terms_alter(&$form, &$form_state, $form_id) {
  $form['actions'][] = array(
    'merge' => array(
      '#type' => 'submit',
      '#value' => t('Merge'),
      '#submit' => array('term_merge_form_taxonomy_overview_terms_merge_submit'),
      '#weight' => 1,
    )
  );

  $form['actions']['submit']['#weight'] = 0;
  $form['actions']['reset_alphabetical']['#weight'] = 2;

}

/**
 *  Submit function for the merge button in the alteration of form form_taxonomy_overview_terms, see above.
 *  Redirect user to the term merge form.
 */
function term_merge_form_taxonomy_overview_terms_merge_submit($form, &$form_state) {
  unset($form_state['storage']);
  $form_state['redirect'] = 'admin/structure/taxonomy/merge/' . $form['#vocabulary']->vid;
}

/**
 *  Implements hook_form().
 *
 *  Menu callback; displays a form with all terms available for merging.
 */
function term_merge_term_merge_form($form, $form_state, $vid) {
  $form = array(
    'term_list' => array(
      '#type' => 'select',
      '#title' => t('Merge terms'),
      '#options' => _term_delete_form_replacement_term_options($vid, 0),
      '#multiple' => TRUE,
      '#required' => TRUE,
      '#attributes' => array('size' => 15),
      '#prefix' => '<div class="merge-container clearfix"><div class="terms-selector">',
    ),

    'replacement_term' => array(
      '#type' => 'select',
      '#title' => t('Into'),
      '#description' => t('Cannot be any of the terms selected in the list to the left.'),
      '#options' => _term_delete_form_replacement_term_options($vid, 0),
      '#prefix' => '</div><div class="merge-selectors">',
    ),

    'replacement_term_new' => array(
      '#type' => 'textfield',
      '#title' => t('Name of new term'),
      '#description' => t('A new term will be created with the specified name.'),
      '#suffix' => '</div></div>',
    ),

    'actions' => array(
      'submit' => array(
        '#type' => 'submit',
        '#value' => t('Merge'),
      )
    )
  );

  $form['#after_build'] = array('_term_merge_form_attach');

  return $form;
}

/**
 *  Submit handler for term_merge_term_merge_form().
 */
function term_merge_term_merge_form_submit($form, &$form_state) {

}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add fields for term merging on the confirm deletion state of the form.
 */
function term_merge_form_taxonomy_form_term_alter(&$form, &$form_state, $form_id) {
  // Only modify the form if it is in the "Confirm Delete" states.
  if (isset($form_state['confirm_delete']) && $form_state['confirm_delete'] === TRUE) {

    $form['description']['#markup'] = $form['description']['#markup'] . '<br /><br />' . t('You can replace any occurrences of the deleted term with another term by specifying the replacement below. This is useful when correcting typos, or to consolidate multiple, synonymous terms.') . '<br /><br />';

    $form['replacement_term_replace'] = array(
      '#type' => 'checkbox',
      '#title' => t('Replace deleted term with:'),
      '#prefix' => '<div>',
    );

    $form['replacement_term'] = array(
      '#type' => 'select',
      '#options' => _term_delete_form_replacement_term_options($form['#vocabulary']->vid, $form['#term']->tid),
      '#suffix' => '</div>',
    );

    $form['replacement_term_new'] = array(
      '#type' => 'textfield',
      '#title' => t('Name of new term'),
    );

    $form['#after_build'] = array('_term_merge_form_attach');

    $form['#submit'] = array('term_merge_form_taxonomy_form_term_submit');
    $form['#validate'] = array('term_merge_form_taxonomy_form_term_validate');
  }
}

/**
 * Validation function for override of form_taxonomy_form_term (see above).
 *
 * Checks to see if I've entered a name for the new term if
 * the user wants to create a new term to merge with.
 */
function term_merge_form_taxonomy_form_term_validate($form, &$form_state) {
  if ($form_state['values']['replacement_term'] == '0' &&
      empty($form_state['values']['replacement_term_new'])) {

    form_set_error('replacement_term_new', t('You must enter a name for the new term.'));
  }
}

/**
 * Submit function for override of form_taxonomy_form_term (see above).
 *
 * If the user choose to create a new tid for merging, create and save a term with the entered name.
 * Call the merge function to merge the replacement term into the deleted term.
 */
function term_merge_form_taxonomy_form_term_submit($form, &$form_state) {
  if ($form_state['values']['replacement_term_replace']) {

    $replacement_term = $form_state['values']['replacement_term'];
    // Create a new tid.
    if ($replacement_term == '0') {

      // get parent of deleted term.
      $deleted_parent_result = db_select('taxonomy_term_hierarchy', 'tth')
        ->fields('tth', array('parent'))
        ->condition('tid' , $form['#term']->tid)
        ->execute()
        ->fetchAssoc();

      $new_term = new stdClass();
      $new_term->name = check_plain($form_state['values']['replacement_term_new']);
      $new_term->vid = $form['#vocabulary']->vid;
      $new_term->parent = $deleted_parent_result['parent'];
      $new_term->vocabulary_machine_name = $form['#vocabulary']->machine_name;
      $new_term->description = '';

      taxonomy_term_save((object) $new_term);

      $dest_tid = $new_term->tid;
    }
    else {  // Else the $replacement_term will contain the tid of the new term.
      $dest_tid = $replacement_term;
    }

    // Merge.
    term_merge_merge($form['#term']->tid, $dest_tid);
  }
  else {
    // Continue as the confirm deletion form would normally.
    taxonomy_term_confirm_delete_submit($form, $form_state);
  }
}


/**
 *  Merge source terms into one destination term.
 * @param $source
 *    A single term tid or an array of term tids to be merged.
 * @param $dest
 *    The tid of the term to merge sources into.
 */
function term_merge_merge($source, $dest) {
  // Create an array of source if it isn't already one.
  if (!is_array($source)) {
    $source = array($source);
  }

  // Create a skeleton for the merging batch.
  $update_batch = array(
    'title' => t('Merging terms'),
    'operations' => array(),
    'finished' => '_term_merge_merge_finished',
  );


  // For every field existing on the site.
  foreach (field_info_fields() as $key => $field) {

    if ($field['type'] == 'taxonomy_term_reference') {
      $table_name = 'field_data_' . $key;
      $tid_field = $key . '_tid';

      $update_data = array();
      foreach ($source as $source_tid) {

        // Get data from fields previously containing a reference to the deleted term.
        $fields_result = db_select($table_name, 'df')
          ->fields('df', array('entity_type', 'entity_id', 'delta'))
          ->condition($tid_field, $source_tid)
          ->execute();

        // Collect update data form the batch process and group them by their entity.
        foreach ($fields_result as $field_row) {
          $batch_key = $field_row->entity_type . '_' . $field_row->entity_id;
          $update_data[$batch_key][] = array(
            'field_name' => $key,
            'delta' => $field_row->delta,
            'tid' => $dest,
          );
        }
      }

      // Create a batch processing step for every entity that needs an update.
      foreach ($update_data as $key => $batch_data) {
        $delimiter_pos = strripos($key, '_');
        $type = drupal_substr($key, 0, $delimiter_pos);
        $id = drupal_substr($key, $delimiter_pos + 1);

        $batch_data = array(
          'entity_type' => $type,
          'entity_id' => $id,
          'merged_tid' => $source_tid,
          'data' => $batch_data
        );
        $update_batch['operations'][] = array(
          '_term_merge_merge_insert_field_values',
          array($batch_data)
        );
      }
    }
  }

  // Initialize the batch process.
  batch_set($update_batch);
}

/**
 *  Batch operation for adding field values into entities.
 *
 *  Loads the entity specified in $update_data and add the term reference
 *  to all fields specified in $update_data['data'].
 */
function _term_merge_merge_insert_field_values($update_data, &$context) {
  // Extract entity information.
  $entity_type = $update_data['entity_type'];
  $entity_id = $update_data['entity_id'];

  // Load the entity.
  $entity = entity_load($entity_type, array($entity_id));
  $entity = $entity[$entity_id];

  // For every field that's affected.
  foreach ($update_data['data'] as $i => &$update_data_arr) {

    // Reverse the fields so that the highest delta comes first.
    // This way they will be spliced into the correct position.
    $update_data_arr = array_reverse($update_data_arr);

    // Get all language arrays for the entity fields.
    $entity_field_langs = &$entity->{$update_data_arr['field_name']};

    // For each language array in the field.
    foreach ($entity_field_langs as &$entity_field_lang_values) {

      // See if the replacement term already exists in the field.
      $exist = FALSE;
      foreach ($entity_field_lang_values as $value) {
        if ($value['tid'] == $update_data_arr['tid']) {
          $exist = TRUE;
          break;
        }
      }

      // Insert the new field value at it's correct position if the replacement tid doesn't already exist.
      if (!$exist) {
        array_splice(
          $entity_field_lang_values,
          $update_data_arr['delta'], 0,
            array(array('tid' => $update_data_arr['tid']))
        );
      }
    }

    if (array_search($update_data['merged_tid'], $context['results']['merged_terms']) === FALSE) {
      $context['results']['merged_terms'][] = $update_data['merged_tid'];
    }

    $context['results'][] = 'Added term with tid ' . $update_data_arr['tid'] . ' to field ' . $update_data_arr['field_name'] . ' in ' . $entity_type . ' ' . $entity_id;
  }

  // Save the new field values.
  field_attach_update($entity_type, $entity);
}

function _term_merge_merge_finished($success, $results, $operations) {
  if ($success) {
    $message = format_plural(max(0, count($results) - 1), 'Merged one occurrence.', '@count occurrences merged.');
  }
  else {
    $message = t('Finished with an error.');
  }
  drupal_set_message($message);

  // Delete merged terms on success. We don't want to do this earlier if something went wrong during the batch process.
  if ($success) {
    foreach ($results['merged_terms'] as $merged_term) {
      taxonomy_term_delete($merged_term);
    }
  }
}

/**
 *  Returns values for the replacement_term select box in the form (see form builder at top).
 *  Don't return the value for the term that will be deleted.
 */
function _term_delete_form_replacement_term_options($vid, $deleted_term_tid) {
  $tree = taxonomy_get_tree($vid);
  foreach ($tree as $i => $term) {
    if ($deleted_term_tid != $term->tid) {
      $options[$term->tid] = $term->name;
    }
  }

  $options['0'] = t('New term, specified below');

  return $options;
}


/**
 *  Add necessary JavaScript and css to the form.
 */
function _term_merge_form_attach($form_element) {
  if ($form_element['#id'] == 'term-merge-term-merge-form') {
    drupal_add_js(drupal_get_path('module', 'term_merge') . '/term_merge.js');
  }
  else if ($form_element['#id'] == 'taxonomy-form-term') {
    drupal_add_js(drupal_get_path('module', 'term_merge') . '/term_merge_deletion.js');
  }

  drupal_add_css(drupal_get_path('module', 'term_merge') . '/term_merge.css');

  return $form_element;
}

