<?php

/**
 * @file
 * Install, uninstall, and update hooks of the module.
 */

/**
 * Convert variables to config.
 */
function term_merge_update_1000() {
  $config = config('term_merge.settings');
  $config->set('select_limit', update_variable_get('term_merge_select_limit', 200));
  $config->set('default_redirect', update_variable_get('term_merge_default_redirect', -1));
  $config->save();
  update_variable_del('term_merge_select_limit');
  update_variable_del('term_merge_default_redirect');
}
