<?php
// $Id$

/**
 * @file
 * TODO: Create a simple contact form block.
 */
 
/**
 * Implements hook_menu().
 */
function term_delete_replace_menu() {
  $items['taxonomyreplace/autocomplete/%'] = array(
    'title' => 'Autocomplete taxonomy replace',
    'page callback' => 'term_delete_replace_term_autocomplete',
    'access arguments' => array('access content'),
    'page arguments' => array(2),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

/**
*	Implements hook_form_alter().
*/
function term_delete_replace_form_taxonomy_form_term_alter(&$form, &$form_state, $form_id) {
	if (isset($form['delete'])) {
		
		array_unshift($form['#submit'], 'term_delete_replace_form_taxonomy_form_term_submit');
		
		$form['description']['#markup'] = t($form['description']['#markup'] . '<br /><br />' . t('You can replace any occurrences of the deleted term with another term by specifying the replacement term below. This is useful when correcting typos, or to consolidate multiple synonymous terms.')); 
		
		$form['replacement_term'] = array(
			'#type' => 'textfield',
			'#title' => t('Replacement term'),
			'#autocomplete_path' => 'taxonomyreplace/autocomplete/' . $form['#vocabulary']->vid,
		);
	}
}

/**
*	Adds te chosen term to all nodes that was using the deleted term.
* If the chosen term doesn't exist, add it to the vocabulary first.
*/
function term_delete_replace_form_taxonomy_form_term_submit($form, &$form_state) {
	if (strlen($form_state['values']['replacement_term']) > 0) {
		$term = null;
		
		$existing_term = taxonomy_get_term_by_name($form_state['values']['replacement_term']);
		foreach ($existing_term as $potential) {
			if ($potential->vocabulary_machine_name == $form['#vocabulary']->machine_name && 
				$potential->name == $form_state['values']['replacement_term']) {
					$term = $potential;
			}
		}
		
		// ToDo: Add behaviour when the administrator tries to replace references to the deleted term with references to that same term.
		/*
		if ($term && $term->tid == $form['#term']->tid) {
			form_set_error('replacement_term', t('Cannot replace the a deleted term with itself.'));
			$form_state['values']['delete'] = FALSE;
			return;			
		} else {
			$form_state['rebuild'] = FALSE;
			$form_state['confirm_delete'] = FALSE;
		}
		*/
		
		// Create the term if it does'nt exist.
		if (!$term) {
			$term = new stdClass();
			$term->name = $form_state['values']['replacement_term'];
			$term->description = NULL;
			$term->format = filter_fallback_format();
			$term->weight = -10;
			$term->vid = $form['#vocabulary']->vid;
			$term->vocabulary_machine_name = $form['#vocabulary']->machine_name;
			
	    $status = taxonomy_term_save($term);
	    
	    drupal_set_message(t('Created term %termname.', array	('%termname' => $term->name)));
		}
		
		$related_nodes_data = db_select('taxonomy_index', 'ti')
			->fields('ti', array('nid', 'created', 'sticky'))
			->condition('tid', $form['#term']->tid)
	  	->execute();
	  
	  // If there are any nodes containing the deleted term, add the replacement term to them.
	  if (!empty($related_nodes_data)) {
			$insert_query = db_insert('taxonomy_index')->fields(array('nid', 'tid', 'sticky', 'created', ));
	    foreach ($related_nodes_data as $node_data) {
	    	$node = node_load($node_data->nid, null, true);
	    		    	
	    	// Find the vocabulary fields containing the deleted term tid.
	    	$vocabulary_fields = _term_delete_replace_get_vocabulary_fields($node, $form['#term']->tid);
	    	
	    	if (!empty($vocabulary_fields)) {
	    		// Add the replacement term to the fields containining the deleted one.
	    		foreach($vocabulary_fields as $fieldname) {
	    			// ToDo: Why do I have to use array_unshift? Else the field api will remove the data for the wrong field in the field's table.
	    			// ToDo: Is the language of the term always the same as the language of the node?
	    			array_unshift($node->{$fieldname}[$node->language], array('tid' => $term->tid));
	    		}
	    	} else {
	    		drupal_set_message(t('Could\'nt find any field containing the deleted term tid, term references was not replaced.'), 'error');
	    		return;
	    	}
	    	
	    	// Save the node with the new replacement term added.
				node_save((object) $node);
	    }
		}
		
		drupal_set_message(
			t(
				'Added term reference "@replace_name" to all fields referencing the deleted term',
				array(
					'@replace_name' => $form_state['values']['replacement_term'],
				)
			)
		);
  }
}

/**
*	Autocomplete function for the replacement term textfield.
*/
function term_delete_replace_term_autocomplete($vid, $typed = '') {

	$tree = taxonomy_get_tree($vid);	
	$output = array();
	foreach ($tree as $i => $term) {
		$tn = $term->name;
		if (strpos(strtolower($tn), strtolower($typed)) !== FALSE) {
			// Term names containing commas or quotes must be wrapped in quotes.
			if (strpos($tn, ',') !== FALSE || strpos($tn, '"') !== FALSE) {
        $tn = '"' . str_replace('"', '""', $tn) . '"';
      }
			$output[$tn] = $tn;
		}
	}

	drupal_json_output($output);
}

/**
*	Helpet function getting the vocabulary fields containing the term with specified tid.
*/
function _term_delete_replace_get_vocabulary_fields($node, $tid) {
	$fields = array();
	foreach ($node as $key => $item) {
		if (is_array($item) && isset($item[$node->language])) {
			foreach ($item[$node->language] as $fieldValue) {
				if (isset($fieldValue['tid']) && $fieldValue['tid'] == $tid) {
					$fields[] = $key;
				}
			}
		}
	}
	return $fields;
}